### ISSUE TITLE
Failing tests: testAcronymsCategories() & testGettingACategoriesAcronymsFromTheAPI()

### ISSUE THREAD

**Issue by marc-medley** [raywenderlich/vapor-til#3]
The `Tests/AppTests/` `testAcronymsCategories()` and `testGettingACategoriesAcronymsFromTheAPI()` FAIL with the following error: 

> [ ERROR ] SQLiteError.warning: Could not convert to Int: 49AAF3DF-B1C6-4335-A8F1-BFB0FA7C3513 (SQLiteData.swift:197)

**Configuration**

The `vapor-til` package was _minimally_ modified to use SQLite instead of PostgreSQL.  _Other than the switch from PostgreSQL to SQLite, no changes have been made to `vapor-til`._

I've not tested with PostgreSQL to know if the same tests pass or fail when using PostgreSQL.

**Possible Fix?**

The tests will pass with the `AcronymCategoryPivot` `id` is switch from `UUID` to `Int`.

_AcronymCategoryPivot.swift_

``` swift
final class AcronymCategoryPivot: SQLiteUUIDPivot {
    var id: UUID? // TESTS FAIL
```

``` swift
final class AcronymCategoryPivot: SQLitePivot {
    var id: Int? // TESTS PASS
```

**Scenario Discussion/Puzzle**

Is there some reason that `UUID` needed to be changed to `Int` for the tests to pass? 

Where in does this issue likely reside:

A. `vapor-til` should be using `Int` instead of `UUID` for the Pivot `id` (for some reason)?, or
B. `FluentSQLite` does not support `UUID` for  the pivot `id`?, or
C. `FluentSQLite` *should* support `UUID` for pivot `id`, therefore an issue needs to be opened on `vapor/fluent-sqlite`?, or
D. something else?

**Comment by 0xTim** [comment]
@marc-medley this issue has been around for a while and I think is waiting on a fix in SQLite to be tagged. The original issue was raised [here](https://github.com/vapor/sqlite/issues/32).

I'll close this issue as it should be fixed when the linked issue is closed and the Vapor TIL app uses Postgres which doesn't have this bug.
