### ISSUE TITLE
Add references

### ISSUE THREAD

**Issue by grosch** [raywenderlich/vapor-til#4]
Tim, since this is a teaching example I think you should implement the prepare on your models that reference other tables and create the `builder.reference` call so that people see how to do it.

https://github.com/raywenderlich/vapor-til/blob/b7d7326f6d3cc6d7ee23357f58ee1810fcc717c1/Sources/App/Models/Token.swift#L45

**Comment by 0xTim** [comment]
Resolved with https://github.com/raywenderlich/vapor-til/commit/d81a5856cb7168a7c927fd876406451626acbe7b
