### ISSUE TITLE
Problems with snake case encoding/decoding

### ISSUE THREAD

**Issue by gperdomor** [raywenderlich/vapor-til#5]
Hi, in the models we have a properties like `userID`, `acronymID`and `categoryID` which cause some problems during test if you set the key decoding/encoding strategy to snake case...

The problem is not related to Vapor, is a swift issue...

You can validate with a playground with this code or just change the content config in the `configure.swift` file

```swift
import Foundation

struct Token: Codable {
    var userID: Int
}

let decoder = JSONDecoder()
let encoder = JSONEncoder()

decoder.keyDecodingStrategy = .convertFromSnakeCase
encoder.keyEncodingStrategy = .convertToSnakeCase

let origToken = Token(userID: 5)

let tokenData = try encoder.encode(origToken)

do {
    let decoded = try decoder.decode(Token.self, from: tokenData)
    print(decoded)
} catch {
    print(error)
}
```

Maybe should be a good idea mention this in the chapters :D

**Comment by 0xTim** [comment]
@gperdomor it's slightly out of scope of the book for now (not helped by `keyEncodingStrategy` not being implemented on Linux yet 😒 

There are other places to add it though, which we'll consider!
